# Form implementation generated from reading ui file 'cdxoataikhoan_form.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_cdxoataikhoan_form(object):
    def setupUi(self, cdxoataikhoan_form):
        cdxoataikhoan_form.setObjectName("cdxoataikhoan_form")
        cdxoataikhoan_form.resize(480, 351)
        cdxoataikhoan_form.setStyleSheet("background-color: rgb(224, 243, 253);")
        self.centralwidget = QtWidgets.QWidget(parent=cdxoataikhoan_form)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_return = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_return.setGeometry(QtCore.QRect(0, 0, 31, 31))
        self.btn_return.setStyleSheet("background-color: rgb(154, 205, 244);")
        self.btn_return.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/ic_return.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_return.setIcon(icon)
        self.btn_return.setObjectName("btn_return")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 480, 31))
        self.label.setStyleSheet("background-color: rgb(154, 205, 244);\n"
"font: 16pt \"Cambria\";")
        self.label.setObjectName("label")
        self.lbl_xoatk = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_xoatk.setGeometry(QtCore.QRect(80, 80, 321, 201))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_xoatk.setFont(font)
        self.lbl_xoatk.setStyleSheet("border-radius:10px;\n"
"font: 13pt \"Cambria\";\n"
"background-color: rgb(146, 214, 255);")
        self.lbl_xoatk.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.lbl_xoatk.setObjectName("lbl_xoatk")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 120, 281, 91))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-radius:10px;\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.btn_huybo = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_huybo.setGeometry(QtCore.QRect(130, 230, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_huybo.setFont(font)
        self.btn_huybo.setStyleSheet("background-color: rgb(255, 194, 209);")
        self.btn_huybo.setObjectName("btn_huybo")
        self.btn_xoa = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_xoa.setGeometry(QtCore.QRect(260, 230, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_xoa.setFont(font)
        self.btn_xoa.setStyleSheet("background-color: rgb(255, 194, 209);")
        self.btn_xoa.setObjectName("btn_xoa")
        self.label.raise_()
        self.btn_return.raise_()
        self.lbl_xoatk.raise_()
        self.label_2.raise_()
        self.btn_huybo.raise_()
        self.btn_xoa.raise_()
        cdxoataikhoan_form.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=cdxoataikhoan_form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 18))
        self.menubar.setObjectName("menubar")
        cdxoataikhoan_form.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=cdxoataikhoan_form)
        self.statusbar.setObjectName("statusbar")
        cdxoataikhoan_form.setStatusBar(self.statusbar)

        self.retranslateUi(cdxoataikhoan_form)
        QtCore.QMetaObject.connectSlotsByName(cdxoataikhoan_form)

    def retranslateUi(self, cdxoataikhoan_form):
        _translate = QtCore.QCoreApplication.translate
        cdxoataikhoan_form.setWindowTitle(_translate("cdxoataikhoan_form", "Xóa tài khoản"))
        self.label.setText(_translate("cdxoataikhoan_form", "<html><head/><body><p align=\"center\">Tài khoản và bảo mật</p></body></html>"))
        self.lbl_xoatk.setText(_translate("cdxoataikhoan_form", "Xóa tài khoản"))
        self.label_2.setText(_translate("cdxoataikhoan_form", "Bạn có chắc chắn muốn xóa toàn bộ dữ liệu \n"
"ứng dụng và tài khoản vĩnh viễn không?"))
        self.btn_huybo.setText(_translate("cdxoataikhoan_form", "Hủy bỏ"))
        self.btn_xoa.setText(_translate("cdxoataikhoan_form", "Xóa tài khoản"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cdxoataikhoan_form = QtWidgets.QMainWindow()
    ui = Ui_cdxoataikhoan_form()
    ui.setupUi(cdxoataikhoan_form)
    cdxoataikhoan_form.show()
    sys.exit(app.exec())
