# Form implementation generated from reading ui file 'chat_form.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_chat_form(object):
    def setupUi(self, chat_form):
        chat_form.setObjectName("chat_form")
        chat_form.resize(480, 351)
        chat_form.setMinimumSize(QtCore.QSize(480, 351))
        chat_form.setMaximumSize(QtCore.QSize(480, 351))
        chat_form.setStyleSheet("background-color: rgb(224, 243, 253)")
        self.centralwidget = QtWidgets.QWidget(parent=chat_form)
        self.centralwidget.setObjectName("centralwidget")
        self.lblchat = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblchat.setGeometry(QtCore.QRect(0, 0, 480, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(16)
        self.lblchat.setFont(font)
        self.lblchat.setStyleSheet("background-color: rgb(154, 205, 244)")
        self.lblchat.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblchat.setObjectName("lblchat")
        self.btn_return = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_return.setGeometry(QtCore.QRect(0, 0, 31, 31))
        self.btn_return.setStyleSheet("background-color: rgb(154, 205, 244)")
        self.btn_return.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/ic_return.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_return.setIcon(icon)
        self.btn_return.setObjectName("btn_return")
        self.txtnhaptinnhan = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtnhaptinnhan.setGeometry(QtCore.QRect(0, 270, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtnhaptinnhan.setFont(font)
        self.txtnhaptinnhan.setStyleSheet("background-color: rgb(171, 200, 223);\n"
"border-radius: 36px\n"
"")
        self.txtnhaptinnhan.setText("")
        self.txtnhaptinnhan.setObjectName("txtnhaptinnhan")
        self.tbnguitinnhan = QtWidgets.QPushButton(parent=self.centralwidget)
        self.tbnguitinnhan.setGeometry(QtCore.QRect(450, 270, 31, 31))
        self.tbnguitinnhan.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/ic_send.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbnguitinnhan.setIcon(icon1)
        self.tbnguitinnhan.setObjectName("tbnguitinnhan")
        self.tbthoptinnhan = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.tbthoptinnhan.setGeometry(QtCore.QRect(0, 30, 481, 241))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tbthoptinnhan.setFont(font)
        self.tbthoptinnhan.setObjectName("tbthoptinnhan")
        chat_form.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=chat_form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 18))
        self.menubar.setObjectName("menubar")
        chat_form.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=chat_form)
        self.statusbar.setObjectName("statusbar")
        chat_form.setStatusBar(self.statusbar)

        self.retranslateUi(chat_form)
        QtCore.QMetaObject.connectSlotsByName(chat_form)

    def retranslateUi(self, chat_form):
        _translate = QtCore.QCoreApplication.translate
        chat_form.setWindowTitle(_translate("chat_form", "Chat"))
        self.lblchat.setText(_translate("chat_form", "<html><head/><body><p>Chat</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    chat_form = QtWidgets.QMainWindow()
    ui = Ui_chat_form()
    ui.setupUi(chat_form)
    chat_form.show()
    sys.exit(app.exec())
