# Form implementation generated from reading ui file 'dangnhap_form.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dangnhap_form(object):
    def setupUi(self, dangnhap_form):
        dangnhap_form.setObjectName("dangnhap_form")
        dangnhap_form.resize(480, 351)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(13)
        dangnhap_form.setFont(font)
        dangnhap_form.setStyleSheet("background-color: rgb(224, 243, 253)")
        self.centralwidget = QtWidgets.QWidget(parent=dangnhap_form)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_hotro = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_hotro.setGeometry(QtCore.QRect(120, 40, 231, 271))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(16)
        self.lbl_hotro.setFont(font)
        self.lbl_hotro.setStyleSheet("background-color: rgb(154, 205, 244);\n"
"border-radius: 10px\n"
"")
        self.lbl_hotro.setText("")
        self.lbl_hotro.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_hotro.setObjectName("lbl_hotro")
        self.txttendangnhap = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txttendangnhap.setGeometry(QtCore.QRect(140, 130, 191, 31))
        self.txttendangnhap.setStyleSheet("border-radius: 10px\n"
"")
        self.txttendangnhap.setText("")
        self.txttendangnhap.setObjectName("txttendangnhap")
        self.txtmatkhau = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtmatkhau.setGeometry(QtCore.QRect(140, 180, 191, 31))
        self.txtmatkhau.setStyleSheet("border-radius: 10px\n"
"")
        self.txtmatkhau.setText("")
        self.txtmatkhau.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtmatkhau.setObjectName("txtmatkhau")
        self.btndangnhap = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btndangnhap.setGeometry(QtCore.QRect(190, 230, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.btndangnhap.setFont(font)
        self.btndangnhap.setStyleSheet("background-color: rgb(250, 219, 227)")
        self.btndangnhap.setObjectName("btndangnhap")
        self.btnquenmatkhau = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnquenmatkhau.setGeometry(QtCore.QRect(130, 270, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.btnquenmatkhau.setFont(font)
        self.btnquenmatkhau.setStyleSheet("background-color: rgba(245, 40, 145, 0)")
        self.btnquenmatkhau.setObjectName("btnquenmatkhau")
        self.btndangky = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btndangky.setGeometry(QtCore.QRect(270, 270, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.btndangky.setFont(font)
        self.btndangky.setStyleSheet("background-color: rgba(245, 40, 145, 0)")
        self.btndangky.setObjectName("btndangky")
        self.btnan = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnan.setGeometry(QtCore.QRect(300, 186, 21, 20))
        self.btnan.setStyleSheet("background-color: rgba(245, 40, 145, 0)")
        self.btnan.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/ic_hide.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnan.setIcon(icon)
        self.btnan.setObjectName("btnan")
        self.btnlogo = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnlogo.setGeometry(QtCore.QRect(200, 50, 71, 71))
        self.btnlogo.setStyleSheet("background-color: rgba(245, 40, 145, 0);\n"
"border-radius: 10px")
        self.btnlogo.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/ic_logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnlogo.setIcon(icon1)
        self.btnlogo.setIconSize(QtCore.QSize(40, 50))
        self.btnlogo.setObjectName("btnlogo")
        dangnhap_form.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=dangnhap_form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 18))
        self.menubar.setObjectName("menubar")
        dangnhap_form.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=dangnhap_form)
        self.statusbar.setObjectName("statusbar")
        dangnhap_form.setStatusBar(self.statusbar)

        self.retranslateUi(dangnhap_form)
        QtCore.QMetaObject.connectSlotsByName(dangnhap_form)

    def retranslateUi(self, dangnhap_form):
        _translate = QtCore.QCoreApplication.translate
        dangnhap_form.setWindowTitle(_translate("dangnhap_form", "Đăng nhập"))
        dangnhap_form.setWhatsThis(_translate("dangnhap_form", "<html><head/><body><p><img src=\":/newPrefix/i_chat.png\"/></p></body></html>"))
        self.txttendangnhap.setPlaceholderText(_translate("dangnhap_form", "   Tên đăng nhập"))
        self.txtmatkhau.setPlaceholderText(_translate("dangnhap_form", "   Mật khẩu"))
        self.btndangnhap.setText(_translate("dangnhap_form", "Đăng nhập"))
        self.btnquenmatkhau.setText(_translate("dangnhap_form", "Quên mật khẩu?"))
        self.btndangky.setText(_translate("dangnhap_form", "Đăng ký"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dangnhap_form = QtWidgets.QMainWindow()
    ui = Ui_dangnhap_form()
    ui.setupUi(dangnhap_form)
    dangnhap_form.show()
    sys.exit(app.exec())
