# Form implementation generated from reading ui file 'doimatkhau_form.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_doimatkhau_form(object):
    def setupUi(self, doimatkhau_form):
        doimatkhau_form.setObjectName("doimatkhau_form")
        doimatkhau_form.resize(480, 351)
        doimatkhau_form.setStyleSheet("background-color: rgb(224, 243, 253)")
        self.centralwidget = QtWidgets.QWidget(parent=doimatkhau_form)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_hotro = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_hotro.setGeometry(QtCore.QRect(120, 40, 231, 271))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(16)
        self.lbl_hotro.setFont(font)
        self.lbl_hotro.setStyleSheet("background-color: rgb(154, 205, 244);\n"
"border-radius: 10px\n"
"")
        self.lbl_hotro.setText("")
        self.lbl_hotro.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_hotro.setObjectName("lbl_hotro")
        self.btnlogo = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnlogo.setGeometry(QtCore.QRect(200, 50, 71, 71))
        self.btnlogo.setStyleSheet("background-color: rgba(245, 40, 145, 0);\n"
"border-radius: 10px")
        self.btnlogo.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/ic_logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnlogo.setIcon(icon)
        self.btnlogo.setIconSize(QtCore.QSize(40, 50))
        self.btnlogo.setObjectName("btnlogo")
        self.txtmatkhaumoi = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtmatkhaumoi.setGeometry(QtCore.QRect(140, 140, 191, 31))
        self.txtmatkhaumoi.setStyleSheet("border-radius: 10px\n"
"")
        self.txtmatkhaumoi.setText("")
        self.txtmatkhaumoi.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtmatkhaumoi.setObjectName("txtmatkhaumoi")
        self.txtnhaplaimatkhaumoi = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtnhaplaimatkhaumoi.setGeometry(QtCore.QRect(140, 190, 191, 31))
        self.txtnhaplaimatkhaumoi.setStyleSheet("border-radius: 10px\n"
"")
        self.txtnhaplaimatkhaumoi.setText("")
        self.txtnhaplaimatkhaumoi.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtnhaplaimatkhaumoi.setObjectName("txtnhaplaimatkhaumoi")
        self.btnanmatkhaucu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnanmatkhaucu.setGeometry(QtCore.QRect(300, 145, 21, 20))
        self.btnanmatkhaucu.setStyleSheet("background-color: rgba(245, 40, 145, 0)")
        self.btnanmatkhaucu.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/ic_hide.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnanmatkhaucu.setIcon(icon1)
        self.btnanmatkhaucu.setObjectName("btnanmatkhaucu")
        self.btnanmatkhaumoi = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnanmatkhaumoi.setGeometry(QtCore.QRect(300, 196, 21, 20))
        self.btnanmatkhaumoi.setStyleSheet("background-color: rgba(245, 40, 145, 0)")
        self.btnanmatkhaumoi.setText("")
        self.btnanmatkhaumoi.setIcon(icon1)
        self.btnanmatkhaumoi.setObjectName("btnanmatkhaumoi")
        self.btndoimatkhau = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btndoimatkhau.setGeometry(QtCore.QRect(190, 240, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.btndoimatkhau.setFont(font)
        self.btndoimatkhau.setStyleSheet("background-color: rgb(250, 219, 227)")
        self.btndoimatkhau.setObjectName("btndoimatkhau")
        self.btndangky = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btndangky.setGeometry(QtCore.QRect(120, 280, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.btndangky.setFont(font)
        self.btndangky.setStyleSheet("background-color: rgba(245, 40, 145, 0)")
        self.btndangky.setObjectName("btndangky")
        self.btn_return = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_return.setGeometry(QtCore.QRect(122, 41, 30, 30))
        self.btn_return.setStyleSheet("background-color: rgba(245, 40, 145, 0)")
        self.btn_return.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/ic_return.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_return.setIcon(icon2)
        self.btn_return.setObjectName("btn_return")
        doimatkhau_form.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=doimatkhau_form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 18))
        self.menubar.setObjectName("menubar")
        doimatkhau_form.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=doimatkhau_form)
        self.statusbar.setObjectName("statusbar")
        doimatkhau_form.setStatusBar(self.statusbar)

        self.retranslateUi(doimatkhau_form)
        QtCore.QMetaObject.connectSlotsByName(doimatkhau_form)

    def retranslateUi(self, doimatkhau_form):
        _translate = QtCore.QCoreApplication.translate
        doimatkhau_form.setWindowTitle(_translate("doimatkhau_form", "Đổi mật khẩu"))
        self.txtmatkhaumoi.setPlaceholderText(_translate("doimatkhau_form", "   Mật khẩu mới"))
        self.txtnhaplaimatkhaumoi.setPlaceholderText(_translate("doimatkhau_form", "   Nhập lại mật khẩu mới"))
        self.btndoimatkhau.setText(_translate("doimatkhau_form", "Đổi mật khẩu"))
        self.btndangky.setText(_translate("doimatkhau_form", "Bạn chưa có tài khoản?                                   Đăng ký"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    doimatkhau_form = QtWidgets.QMainWindow()
    ui = Ui_doimatkhau_form()
    ui.setupUi(doimatkhau_form)
    doimatkhau_form.show()
    sys.exit(app.exec())
