# Form implementation generated from reading ui file 'gdhtcauhoithuonggap.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_gdhtcauhoithuonggap(object):
    def setupUi(self, gdhtcauhoithuonggap):
        gdhtcauhoithuonggap.setObjectName("gdhtcauhoithuonggap")
        gdhtcauhoithuonggap.resize(480, 351)
        gdhtcauhoithuonggap.setStyleSheet("background-color: rgb(224, 243, 253)")
        self.centralwidget = QtWidgets.QWidget(parent=gdhtcauhoithuonggap)
        self.centralwidget.setObjectName("centralwidget")
        self.lblcauhoithuonggap = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblcauhoithuonggap.setGeometry(QtCore.QRect(0, 0, 480, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(16)
        self.lblcauhoithuonggap.setFont(font)
        self.lblcauhoithuonggap.setStyleSheet("background-color:rgb(154, 205, 244)")
        self.lblcauhoithuonggap.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblcauhoithuonggap.setObjectName("lblcauhoithuonggap")
        self.btnmuiten = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnmuiten.setGeometry(QtCore.QRect(0, 0, 31, 31))
        self.btnmuiten.setStyleSheet("background-color: rgb(154, 205, 244)")
        self.btnmuiten.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/i_muiten.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnmuiten.setIcon(icon)
        self.btnmuiten.setObjectName("btnmuiten")
        self.btncauhoi1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btncauhoi1.setGeometry(QtCore.QRect(20, 100, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btncauhoi1.setFont(font)
        self.btncauhoi1.setStyleSheet("background-color: rgb(218, 229, 238);")
        self.btncauhoi1.setObjectName("btncauhoi1")
        self.btncauhoi2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btncauhoi2.setGeometry(QtCore.QRect(20, 150, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btncauhoi2.setFont(font)
        self.btncauhoi2.setStyleSheet("background-color: rgb(218, 229, 238);")
        self.btncauhoi2.setObjectName("btncauhoi2")
        self.btncauhoi3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btncauhoi3.setGeometry(QtCore.QRect(20, 200, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btncauhoi3.setFont(font)
        self.btncauhoi3.setStyleSheet("background-color: rgb(218, 229, 238);")
        self.btncauhoi3.setObjectName("btncauhoi3")
        self.btncauhoi4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btncauhoi4.setGeometry(QtCore.QRect(20, 250, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btncauhoi4.setFont(font)
        self.btncauhoi4.setStyleSheet("background-color: rgb(218, 229, 238);")
        self.btncauhoi4.setObjectName("btncauhoi4")
        self.btncauhoi9 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btncauhoi9.setGeometry(QtCore.QRect(250, 250, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btncauhoi9.setFont(font)
        self.btncauhoi9.setStyleSheet("background-color: rgb(218, 229, 238);")
        self.btncauhoi9.setObjectName("btncauhoi9")
        self.btncauhoi5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btncauhoi5.setGeometry(QtCore.QRect(250, 100, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btncauhoi5.setFont(font)
        self.btncauhoi5.setStyleSheet("background-color: rgb(218, 229, 238);")
        self.btncauhoi5.setObjectName("btncauhoi5")
        self.btncauhoi7 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btncauhoi7.setGeometry(QtCore.QRect(250, 150, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btncauhoi7.setFont(font)
        self.btncauhoi7.setStyleSheet("background-color: rgb(218, 229, 238);")
        self.btncauhoi7.setObjectName("btncauhoi7")
        self.btncauhoi8 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btncauhoi8.setGeometry(QtCore.QRect(250, 200, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btncauhoi8.setFont(font)
        self.btncauhoi8.setStyleSheet("background-color: rgb(218, 229, 238);")
        self.btncauhoi8.setObjectName("btncauhoi8")
        self.lblvande = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblvande.setGeometry(QtCore.QRect(40, 50, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.lblvande.setFont(font)
        self.lblvande.setStyleSheet("background-color: rgb(171, 200, 223);\n"
"border-radius: 10px\n"
"")
        self.lblvande.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblvande.setObjectName("lblvande")
        gdhtcauhoithuonggap.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=gdhtcauhoithuonggap)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 18))
        self.menubar.setObjectName("menubar")
        gdhtcauhoithuonggap.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=gdhtcauhoithuonggap)
        self.statusbar.setObjectName("statusbar")
        gdhtcauhoithuonggap.setStatusBar(self.statusbar)

        self.retranslateUi(gdhtcauhoithuonggap)
        QtCore.QMetaObject.connectSlotsByName(gdhtcauhoithuonggap)

    def retranslateUi(self, gdhtcauhoithuonggap):
        _translate = QtCore.QCoreApplication.translate
        gdhtcauhoithuonggap.setWindowTitle(_translate("gdhtcauhoithuonggap", "gdhtcauhoithuonggap"))
        self.lblcauhoithuonggap.setText(_translate("gdhtcauhoithuonggap", "<html><head/><body><p>Câu hỏi thường gặp</p></body></html>"))
        self.btncauhoi1.setText(_translate("gdhtcauhoithuonggap", "Làm sao để thay đổi đơn vị \n"
" tiền tệ?"))
        self.btncauhoi2.setText(_translate("gdhtcauhoithuonggap", "Ứng dụng có cảnh báo khi  \n"
"tôi chi tiêu vượt mức không?"))
        self.btncauhoi3.setText(_translate("gdhtcauhoithuonggap", "Làm thế nào để liên hệ với \n"
" bộ phận hỗ trợ nếu gặp lỗi?"))
        self.btncauhoi4.setText(_translate("gdhtcauhoithuonggap", "Ứng dụng có thể đề xuất cách cân \n"
"bằng thu nhập và chi tiêu không?"))
        self.btncauhoi9.setText(_translate("gdhtcauhoithuonggap", "Làm sao để đặt giới hạn chi tiêu \n"
" theo ngày hoặc tuần?"))
        self.btncauhoi5.setText(_translate("gdhtcauhoithuonggap", " Tôi quên mật khẩu, làm sao \n"
" để đặt lại mật khẩu?"))
        self.btncauhoi7.setText(_translate("gdhtcauhoithuonggap", "Làm sao để thay đổi đơn vị \n"
" tiền tệ?"))
        self.btncauhoi8.setText(_translate("gdhtcauhoithuonggap", "Làm thế nào để tắt/bật thông \n"
"  báo từ ứng dụng?"))
        self.lblvande.setText(_translate("gdhtcauhoithuonggap", "     Vấn đề bạn cần hỗ trợ?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gdhtcauhoithuonggap = QtWidgets.QMainWindow()
    ui = Ui_gdhtcauhoithuonggap()
    ui.setupUi(gdhtcauhoithuonggap)
    gdhtcauhoithuonggap.show()
    sys.exit(app.exec())
