# Form implementation generated from reading ui file 'gdhtchat.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_gdhtchat(object):
    def setupUi(self, gdhtchat):
        gdhtchat.setObjectName("gdhtchat")
        gdhtchat.resize(480, 351)
        gdhtchat.setStyleSheet("background-color: rgb(224, 243, 253)")
        self.centralwidget = QtWidgets.QWidget(parent=gdhtchat)
        self.centralwidget.setObjectName("centralwidget")
        self.lblchat = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblchat.setGeometry(QtCore.QRect(0, 0, 480, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(16)
        self.lblchat.setFont(font)
        self.lblchat.setStyleSheet("background-color: rgb(154, 205, 244)")
        self.lblchat.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblchat.setObjectName("lblchat")
        self.btnmuiten = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnmuiten.setGeometry(QtCore.QRect(0, 0, 31, 31))
        self.btnmuiten.setStyleSheet("background-color: rgb(154, 205, 244)")
        self.btnmuiten.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/i_muiten.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnmuiten.setIcon(icon)
        self.btnmuiten.setObjectName("btnmuiten")
        self.txtnhaptinnhan = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtnhaptinnhan.setGeometry(QtCore.QRect(0, 270, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtnhaptinnhan.setFont(font)
        self.txtnhaptinnhan.setStyleSheet("background-color: rgb(171, 200, 223);\n"
"border-radius: 36px\n"
"")
        self.txtnhaptinnhan.setText("")
        self.txtnhaptinnhan.setObjectName("txtnhaptinnhan")
        self.tbnguitinnhan = QtWidgets.QPushButton(parent=self.centralwidget)
        self.tbnguitinnhan.setGeometry(QtCore.QRect(450, 270, 31, 31))
        self.tbnguitinnhan.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Downloads/paper-plane-top.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbnguitinnhan.setIcon(icon1)
        self.tbnguitinnhan.setObjectName("tbnguitinnhan")
        self.tbthoptinnhan = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.tbthoptinnhan.setGeometry(QtCore.QRect(0, 30, 481, 241))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tbthoptinnhan.setFont(font)
        self.tbthoptinnhan.setObjectName("tbthoptinnhan")
        gdhtchat.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=gdhtchat)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 18))
        self.menubar.setObjectName("menubar")
        gdhtchat.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=gdhtchat)
        self.statusbar.setObjectName("statusbar")
        gdhtchat.setStatusBar(self.statusbar)

        self.retranslateUi(gdhtchat)
        QtCore.QMetaObject.connectSlotsByName(gdhtchat)

    def retranslateUi(self, gdhtchat):
        _translate = QtCore.QCoreApplication.translate
        gdhtchat.setWindowTitle(_translate("gdhtchat", "gdhtchat"))
        self.lblchat.setText(_translate("gdhtchat", "<html><head/><body><p>Chat</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gdhtchat = QtWidgets.QMainWindow()
    ui = Ui_gdhtchat()
    ui.setupUi(gdhtchat)
    gdhtchat.show()
    sys.exit(app.exec())
