# Form implementation generated from reading ui file 'C:\PyCharmProjects\finalproject\canhbao\lightmode_canhbao_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(588, 203)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        Dialog.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        self.btn_exit = QtWidgets.QPushButton(parent=Dialog)
        self.btn_exit.setGeometry(QtCore.QRect(550, 10, 31, 28))
        self.btn_exit.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\PyCharmProjects\\finalproject\\canhbao\\../../../Users/DELL/Downloads/close.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_exit.setIcon(icon)
        self.btn_exit.setFlat(True)
        self.btn_exit.setObjectName("btn_exit")
        self.warning_content = QtWidgets.QLabel(parent=Dialog)
        self.warning_content.setGeometry(QtCore.QRect(60, 80, 471, 91))
        self.warning_content.setStyleSheet("background-color: rgb(255, 194, 209);")
        self.warning_content.setObjectName("warning_content")
        self.warning_title = QtWidgets.QLabel(parent=Dialog)
        self.warning_title.setGeometry(QtCore.QRect(-60, 40, 751, 156))
        self.warning_title.setContentsMargins(-10,10,0,0)
        font = QtGui.QFont()
        font.setKerning(True)
        self.warning_title.setFont(font)
        self.warning_title.setStyleSheet("background-color: rgb(255, 194, 209);")
        self.warning_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.warning_title.setObjectName("warning_title")
        self.warning_icon = QtWidgets.QLabel(parent=Dialog)
        self.warning_icon.setGeometry(QtCore.QRect(230, 45, 31, 31))
        self.warning_icon.setStyleSheet("background-color: rgb(255, 194, 209);")
        self.warning_icon.setText("")
        self.warning_icon.setPixmap(QtGui.QPixmap("C:\\PyCharmProjects\\finalproject\\canhbao\\../../../Users/DELL/Downloads/warning.png"))
        self.warning_icon.setScaledContents(True)
        self.warning_icon.setObjectName("warning_icon")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(-13, 40, 21, 161))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(580, 40, 21, 161))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.lb_app_name = QtWidgets.QLabel(parent=Dialog)
        self.lb_app_name.setGeometry(QtCore.QRect(40, 4, 91, 31))
        self.lb_app_name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lb_app_name.setText("")
        self.lb_app_name.setPixmap(QtGui.QPixmap("C:\\PyCharmProjects\\finalproject\\canhbao\\../../../Users/DELL/Downloads/ic_logo_name.png"))
        self.lb_app_name.setScaledContents(True)
        self.lb_app_name.setObjectName("lb_app_name")
        self.app_logo = QtWidgets.QLabel(parent=Dialog)
        self.app_logo.setGeometry(QtCore.QRect(5, 4, 41, 31))
        self.app_logo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.app_logo.setText("")
        self.app_logo.setPixmap(QtGui.QPixmap("C:\\PyCharmProjects\\finalproject\\canhbao\\../../../Users/DELL/Downloads/logo(lightmode).png"))
        self.app_logo.setScaledContents(True)
        self.app_logo.setObjectName("app_logo")
        self.warning_title.raise_()
        self.btn_exit.raise_()
        self.warning_content.raise_()
        self.warning_icon.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.lb_app_name.raise_()
        self.app_logo.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.warning_content.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#0a102a;\">Bạn đã vượt hạn mức rồi, nhưng đừng lo, </span></p><p align=\"center\"><span style=\" font-size:12pt; color:#0a102a;\">cuối tháng mình cùng nhau ăn mì gói nhé! 🍜</span></p></body></html>"))
        self.warning_title.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#0a102a;\">Cảnh báo</span></p></body></html>"))
