# Form implementation generated from reading ui file 'Muc_tieu_tai_chinh_PhatTrienBanThan.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PhatTrienBanThan(object):
    def setupUi(self, PhatTrienBanThan):
        PhatTrienBanThan.setObjectName("PhatTrienBanThan")
        PhatTrienBanThan.resize(481, 351)
        self.centralwidget = QtWidgets.QWidget(parent=PhatTrienBanThan)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 35, 461, 51))
        self.label_2.setStyleSheet("border-radius: 10px")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../ic_nen1.png"))
        self.label_2.setObjectName("label_2")
        self.btnQuayLai = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnQuayLai.setGeometry(QtCore.QRect(0, 0, 31, 31))
        self.btnQuayLai.setStyleSheet("background-color: rgba(245, 40, 145, 0);")
        self.btnQuayLai.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../ic_arrow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnQuayLai.setIcon(icon)
        self.btnQuayLai.setObjectName("btnQuayLai")
        self.btnXacNhan = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnXacNhan.setGeometry(QtCore.QRect(80, 240, 151, 32))
        self.btnXacNhan.setStyleSheet("background-color: rgb(255, 194, 209);\n"
"border-radius:10px")
        self.btnXacNhan.setObjectName("btnXacNhan")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 135, 141, 16))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 480, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(154, 205, 244);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.txtTenQuy = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTenQuy.setGeometry(QtCore.QRect(10, 95, 210, 35))
        self.txtTenQuy.setStyleSheet("border-radius:10px;\n"
"background-color: #e9f8ff")
        self.txtTenQuy.setObjectName("txtTenQuy")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(265, 135, 111, 16))
        self.label_4.setObjectName("label_4")
        self.txtNgayBatDau = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.txtNgayBatDau.setGeometry(QtCore.QRect(10, 155, 210, 35))
        self.txtNgayBatDau.setStyleSheet("background-color:#e9f8ff;\n"
"border-radius:10px")
        self.txtNgayBatDau.setObjectName("txtNgayBatDau")
        self.txtSoTienCanGop = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtSoTienCanGop.setGeometry(QtCore.QRect(250, 200, 210, 35))
        self.txtSoTienCanGop.setStyleSheet("border-radius:10px;\n"
"background-color:#e9f8ff\n"
"")
        self.txtSoTienCanGop.setObjectName("txtSoTienCanGop")
        self.txtNgayKetThuc = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.txtNgayKetThuc.setGeometry(QtCore.QRect(260, 155, 210, 35))
        self.txtNgayKetThuc.setStyleSheet("background-color:#e9f8ff;\n"
"border-radius:10px")
        self.txtNgayKetThuc.setObjectName("txtNgayKetThuc")
        self.txtSoTienMucTieu = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtSoTienMucTieu.setGeometry(QtCore.QRect(260, 95, 210, 35))
        self.txtSoTienMucTieu.setStyleSheet("border-radius:10px;\n"
"background-color:#e9f8ff\n"
"")
        self.txtSoTienMucTieu.setObjectName("txtSoTienMucTieu")
        self.btnTinhTien = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnTinhTien.setGeometry(QtCore.QRect(10, 200, 231, 35))
        self.btnTinhTien.setStyleSheet("background-color:#e9f8ff;\n"
"border-radius:10px")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../ic_calculator.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnTinhTien.setIcon(icon1)
        self.btnTinhTien.setObjectName("btnTinhTien")
        self.btnXemLai = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnXemLai.setGeometry(QtCore.QRect(240, 240, 151, 32))
        self.btnXemLai.setStyleSheet("background-color: rgb(255, 194, 209);\n"
"border-radius:10px")
        self.btnXemLai.setObjectName("btnXemLai")
        self.label_2.raise_()
        self.btnXacNhan.raise_()
        self.label_3.raise_()
        self.label.raise_()
        self.txtTenQuy.raise_()
        self.label_4.raise_()
        self.txtNgayBatDau.raise_()
        self.txtSoTienCanGop.raise_()
        self.txtNgayKetThuc.raise_()
        self.txtSoTienMucTieu.raise_()
        self.btnTinhTien.raise_()
        self.btnQuayLai.raise_()
        self.btnXemLai.raise_()
        PhatTrienBanThan.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=PhatTrienBanThan)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 481, 24))
        self.menubar.setObjectName("menubar")
        PhatTrienBanThan.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=PhatTrienBanThan)
        self.statusbar.setObjectName("statusbar")
        PhatTrienBanThan.setStatusBar(self.statusbar)

        self.retranslateUi(PhatTrienBanThan)
        QtCore.QMetaObject.connectSlotsByName(PhatTrienBanThan)

    def retranslateUi(self, PhatTrienBanThan):
        _translate = QtCore.QCoreApplication.translate
        PhatTrienBanThan.setWindowTitle(_translate("PhatTrienBanThan", "Muc_tieu_tai_chinh_PhatTrienBanThan"))
        self.btnXacNhan.setText(_translate("PhatTrienBanThan", "Xác nhận lập quỹ"))
        self.label_3.setText(_translate("PhatTrienBanThan", "Ngày bắt đầu "))
        self.label.setText(_translate("PhatTrienBanThan", "PHÁT TRIỂN BẢN THÂN"))
        self.label_4.setText(_translate("PhatTrienBanThan", "Ngày kết thúc"))
        self.btnTinhTien.setText(_translate("PhatTrienBanThan", "Số tiền bạn cần góp mỗi ngày là:"))
        self.btnXemLai.setText(_translate("PhatTrienBanThan", "Các loại quỹ hiện có"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PhatTrienBanThan = QtWidgets.QMainWindow()
    ui = Ui_PhatTrienBanThan()
    ui.setupUi(PhatTrienBanThan)
    PhatTrienBanThan.show()
    sys.exit(app.exec())
