# Form implementation generated from reading ui file 'Muc_tieu_tai_chinh_AnUongVuiVe.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AnUongVuiVe(object):
    def setupUi(self, AnUongVuiVe):
        AnUongVuiVe.setObjectName("AnUongVuiVe")
        AnUongVuiVe.resize(526, 351)
        self.centralwidget = QtWidgets.QWidget(parent=AnUongVuiVe)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 461, 51))
        self.label_2.setStyleSheet("border-radius: 10px")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../ic_nen1.png"))
        self.label_2.setObjectName("label_2")
        self.txtSoTienCanGop = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtSoTienCanGop.setGeometry(QtCore.QRect(140, 200, 210, 35))
        self.txtSoTienCanGop.setStyleSheet("border-radius:10px;\n"
"background-color:#e9f8ff\n"
"")
        self.txtSoTienCanGop.setObjectName("txtSoTienCanGop")
        self.btnXacNhan = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnXacNhan.setGeometry(QtCore.QRect(80, 250, 151, 32))
        self.btnXacNhan.setStyleSheet("background-color: rgb(255, 194, 209);\n"
"border-radius:10px")
        self.btnXacNhan.setObjectName("btnXacNhan")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(265, 140, 111, 16))
        self.label_4.setObjectName("label_4")
        self.txtNgayBatDau = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.txtNgayBatDau.setGeometry(QtCore.QRect(10, 160, 210, 35))
        self.txtNgayBatDau.setStyleSheet("background-color:#e9f8ff;\n"
"border-radius:10px")
        self.txtNgayBatDau.setObjectName("txtNgayBatDau")
        self.txtNgayKetThuc = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.txtNgayKetThuc.setGeometry(QtCore.QRect(260, 160, 210, 35))
        self.txtNgayKetThuc.setStyleSheet("background-color:#e9f8ff;\n"
"border-radius:10px")
        self.txtNgayKetThuc.setObjectName("txtNgayKetThuc")
        self.txtSoTienMucTieu = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtSoTienMucTieu.setGeometry(QtCore.QRect(260, 100, 210, 35))
        self.txtSoTienMucTieu.setStyleSheet("border-radius:10px;\n"
"background-color:#e9f8ff\n"
"")
        self.txtSoTienMucTieu.setObjectName("txtSoTienMucTieu")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 480, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(154, 205, 244);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 141, 16))
        self.label_3.setObjectName("label_3")
        self.txtTenQuy = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTenQuy.setGeometry(QtCore.QRect(10, 100, 210, 35))
        self.txtTenQuy.setStyleSheet("border-radius:10px;\n"
"background-color: #e9f8ff")
        self.txtTenQuy.setObjectName("txtTenQuy")
        self.btnQuayLai = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnQuayLai.setGeometry(QtCore.QRect(0, 0, 31, 31))
        self.btnQuayLai.setStyleSheet("background-color: rgba(245, 40, 145, 0);")
        self.btnQuayLai.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../ic_arrow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnQuayLai.setIcon(icon)
        self.btnQuayLai.setObjectName("btnQuayLai")
        self.btnXemLai = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnXemLai.setGeometry(QtCore.QRect(240, 250, 151, 32))
        self.btnXemLai.setStyleSheet("background-color: rgb(255, 194, 209);\n"
"border-radius:10px")
        self.btnXemLai.setObjectName("btnXemLai")
        AnUongVuiVe.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=AnUongVuiVe)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 526, 24))
        self.menubar.setObjectName("menubar")
        AnUongVuiVe.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=AnUongVuiVe)
        self.statusbar.setObjectName("statusbar")
        AnUongVuiVe.setStatusBar(self.statusbar)

        self.retranslateUi(AnUongVuiVe)
        QtCore.QMetaObject.connectSlotsByName(AnUongVuiVe)

    def retranslateUi(self, AnUongVuiVe):
        _translate = QtCore.QCoreApplication.translate
        AnUongVuiVe.setWindowTitle(_translate("AnUongVuiVe", "Muc_tieu_tai_chinh_AnUongVuiVe"))
        self.btnXacNhan.setText(_translate("AnUongVuiVe", "Xác nhận lập quỹ"))
        self.label_4.setText(_translate("AnUongVuiVe", "Ngày kết thúc"))
        self.label.setText(_translate("AnUongVuiVe", "ĂN UỐNG VUI VẺ"))
        self.label_3.setText(_translate("AnUongVuiVe", "Ngày bắt đầu "))
        self.btnXemLai.setText(_translate("AnUongVuiVe", "Các loại quỹ hiện có"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AnUongVuiVe = QtWidgets.QMainWindow()
    ui = Ui_AnUongVuiVe()
    ui.setupUi(AnUongVuiVe)
    AnUongVuiVe.show()
    sys.exit(app.exec())
