# Form implementation generated from reading ui file 'phantich.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 351)
        MainWindow.setMinimumSize(QtCore.QSize(480, 351))
        MainWindow.setMaximumSize(QtCore.QSize(480, 351))
        MainWindow.setStyleSheet("background-color: rgb(224, 243, 253);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_sodu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_sodu.setGeometry(QtCore.QRect(10, 40, 90, 51))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_sodu.setFont(font)
        self.btn_sodu.setStyleSheet("background-color: rgb(159, 223, 255);\n"
"color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.btn_sodu.setObjectName("btn_sodu")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 480, 31))
        self.label.setStyleSheet("background-color: rgb(154, 205, 244);\n"
"font: 16pt \"Cambria\";\n"
"color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.btn_return = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_return.setGeometry(QtCore.QRect(0, 0, 31, 31))
        self.btn_return.setStyleSheet("background-color: rgb(154, 205, 244);")
        self.btn_return.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/ic_return.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_return.setIcon(icon)
        self.btn_return.setIconSize(QtCore.QSize(12, 12))
        self.btn_return.setFlat(True)
        self.btn_return.setObjectName("btn_return")
        self.fr_bieudotron = QtWidgets.QFrame(parent=self.centralwidget)
        self.fr_bieudotron.setGeometry(QtCore.QRect(80, 110, 321, 181))
        self.fr_bieudotron.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.fr_bieudotron.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fr_bieudotron.setObjectName("fr_bieudotron")
        self.btn_tongthu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_tongthu.setGeometry(QtCore.QRect(130, 40, 90, 51))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_tongthu.setFont(font)
        self.btn_tongthu.setStyleSheet("background-color: rgb(159, 223, 255);\n"
"color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.btn_tongthu.setObjectName("btn_tongthu")
        self.btn_tietkiem = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_tietkiem.setGeometry(QtCore.QRect(370, 40, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_tietkiem.setFont(font)
        self.btn_tietkiem.setStyleSheet("background-color: rgb(159, 223, 255);\n"
"color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.btn_tietkiem.setObjectName("btn_tietkiem")
        self.btn_tongchi_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_tongchi_2.setGeometry(QtCore.QRect(250, 40, 90, 51))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_tongchi_2.setFont(font)
        self.btn_tongchi_2.setStyleSheet("background-color: rgb(159, 223, 255);\n"
"color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.btn_tongchi_2.setObjectName("btn_tongchi_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_sodu.setText(_translate("MainWindow", "Số dư tổng"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Phân tích</p></body></html>"))
        self.btn_tongthu.setText(_translate("MainWindow", "Tổng thu"))
        self.btn_tietkiem.setText(_translate("MainWindow", "Tiết kiệm"))
        self.btn_tongchi_2.setText(_translate("MainWindow", "Tổng chi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
