# Form implementation generated from reading ui file 'Thong_ke_bao_cao_MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_thong_ke_bao_cao(object):
    def setupUi(self, thong_ke_bao_cao):
        thong_ke_bao_cao.setObjectName("thong_ke_bao_cao")
        thong_ke_bao_cao.resize(480, 341)
        self.centralwidget = QtWidgets.QWidget(parent=thong_ke_bao_cao)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 480, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(154, 205, 244);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.btnBCTC = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnBCTC.setGeometry(QtCore.QRect(10, 180, 210, 130))
        self.btnBCTC.setStyleSheet("background-color: #9acdf4")
        self.btnBCTC.setText("")
        self.btnBCTC.setObjectName("btnBCTC")
        self.btnLSGD = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnLSGD.setGeometry(QtCore.QRect(10, 40, 210, 130))
        self.btnLSGD.setStyleSheet("background-color: #9acdf4\n"
"")
        self.btnLSGD.setText("")
        self.btnLSGD.setObjectName("btnLSGD")
        self.btnDPRR = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDPRR.setGeometry(QtCore.QRect(260, 180, 210, 130))
        self.btnDPRR.setStyleSheet("background-color: #9acdf4")
        self.btnDPRR.setText("")
        self.btnDPRR.setObjectName("btnDPRR")
        self.btnMTTC = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnMTTC.setGeometry(QtCore.QRect(260, 40, 210, 130))
        self.btnMTTC.setStyleSheet("background-color: #9acdf4")
        self.btnMTTC.setText("")
        self.btnMTTC.setObjectName("btnMTTC")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 40, 210, 25))
        self.label_4.setStyleSheet("font:bold;\n"
"background-color: #e9f8ff\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(30, 80, 81, 71))
        self.label_9.setStyleSheet("position: absolute;\n"
"width: 137px;\n"
"height: 137px;\n"
"left: 218px;\n"
"top: 432px;\n"
"\n"
"")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("../ic_report.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_36 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(140, 80, 61, 71))
        self.label_36.setText("")
        self.label_36.setPixmap(QtGui.QPixmap("../ic_time-management.png"))
        self.label_36.setScaledContents(True)
        self.label_36.setObjectName("label_36")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(260, 40, 210, 25))
        self.label_5.setStyleSheet("font:bold;\n"
"background-color: #e9f8ff\n"
"")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 180, 210, 25))
        self.label_6.setStyleSheet("font:bold;\n"
"background-color: #e9f8ff\n"
"")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(260, 180, 210, 25))
        self.label_7.setStyleSheet("font:bold;\n"
"background-color: #e9f8ff\n"
"")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_37 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(270, 80, 81, 71))
        self.label_37.setText("")
        self.label_37.setPixmap(QtGui.QPixmap("../ic_goal.png"))
        self.label_37.setScaledContents(True)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(380, 80, 81, 71))
        self.label_38.setText("")
        self.label_38.setPixmap(QtGui.QPixmap("../ic_goals.png"))
        self.label_38.setScaledContents(True)
        self.label_38.setObjectName("label_38")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 220, 81, 71))
        self.label_10.setStyleSheet("position: absolute;\n"
"width: 137px;\n"
"height: 137px;\n"
"left: 218px;\n"
"top: 432px;\n"
"\n"
"")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("../ic_report_3.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(130, 220, 81, 71))
        self.label_11.setStyleSheet("position: absolute;\n"
"width: 137px;\n"
"height: 137px;\n"
"left: 218px;\n"
"top: 432px;\n"
"\n"
"")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("../ic_report_2.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(270, 220, 81, 71))
        self.label_12.setStyleSheet("position: absolute;\n"
"width: 137px;\n"
"height: 137px;\n"
"left: 218px;\n"
"top: 432px;\n"
"\n"
"")
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("../ic_reputation.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(370, 220, 81, 71))
        self.label_13.setStyleSheet("position: absolute;\n"
"width: 137px;\n"
"height: 137px;\n"
"left: 218px;\n"
"top: 432px;\n"
"\n"
"")
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("../ic_good-business.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.btnQuayLai = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnQuayLai.setGeometry(QtCore.QRect(0, 0, 31, 31))
        self.btnQuayLai.setStyleSheet("background-color: rgba(245, 40, 145, 0);")
        self.btnQuayLai.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../ic_arrow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnQuayLai.setIcon(icon)
        self.btnQuayLai.setObjectName("btnQuayLai")
        self.label.raise_()
        self.btnBCTC.raise_()
        self.btnLSGD.raise_()
        self.btnDPRR.raise_()
        self.btnMTTC.raise_()
        self.label_4.raise_()
        self.label_9.raise_()
        self.label_36.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_37.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.btnQuayLai.raise_()
        self.label_38.raise_()
        thong_ke_bao_cao.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=thong_ke_bao_cao)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 24))
        self.menubar.setObjectName("menubar")
        thong_ke_bao_cao.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=thong_ke_bao_cao)
        self.statusbar.setObjectName("statusbar")
        thong_ke_bao_cao.setStatusBar(self.statusbar)

        self.retranslateUi(thong_ke_bao_cao)
        QtCore.QMetaObject.connectSlotsByName(thong_ke_bao_cao)

    def retranslateUi(self, thong_ke_bao_cao):
        _translate = QtCore.QCoreApplication.translate
        thong_ke_bao_cao.setWindowTitle(_translate("thong_ke_bao_cao", "Thống kê báo cáo "))
        self.label.setText(_translate("thong_ke_bao_cao", "THỐNG KÊ BÁO CÁO"))
        self.label_4.setText(_translate("thong_ke_bao_cao", "Xem lịch sử giao dịch"))
        self.label_5.setText(_translate("thong_ke_bao_cao", "Mục tiêu tài chính"))
        self.label_6.setText(_translate("thong_ke_bao_cao", "Báo cáo tài chính"))
        self.label_7.setText(_translate("thong_ke_bao_cao", "Đề xuất chi tiêu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    thong_ke_bao_cao = QtWidgets.QMainWindow()
    ui = Ui_thong_ke_bao_cao()
    ui.setupUi(thong_ke_bao_cao)
    thong_ke_bao_cao.show()
    sys.exit(app.exec())
