# Form implementation generated from reading ui file 'vilienket_form.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_vilienket_form(object):
    def setupUi(self, vilienket_form):
        vilienket_form.setObjectName("vilienket_form")
        vilienket_form.resize(480, 351)
        vilienket_form.setStyleSheet("background-color: rgb(224, 243, 253);")
        self.centralwidget = QtWidgets.QWidget(parent=vilienket_form)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_return = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_return.setGeometry(QtCore.QRect(0, 0, 31, 31))
        self.btn_return.setStyleSheet("background-color: rgb(154, 205, 244);")
        self.btn_return.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Downloads/left-arrow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_return.setIcon(icon)
        self.btn_return.setObjectName("btn_return")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 480, 31))
        self.label.setStyleSheet("background-color: rgb(154, 205, 244);\n"
"font: 16pt \"Cambria\";")
        self.label.setObjectName("label")
        self.tbl_lienketnh = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tbl_lienketnh.setGeometry(QtCore.QRect(40, 70, 401, 192))
        self.tbl_lienketnh.setColumnCount(4)
        self.tbl_lienketnh.setObjectName("tbl_lienketnh")
        self.tbl_lienketnh.setRowCount(0)
        self.btn_lktkmoi = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_lktkmoi.setGeometry(QtCore.QRect(10, 270, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_lktkmoi.setFont(font)
        self.btn_lktkmoi.setStyleSheet("background-color: rgb(255, 194, 209);\n"
"")
        self.btn_lktkmoi.setObjectName("btn_lktkmoi")
        self.btn_khoatk = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_khoatk.setGeometry(QtCore.QRect(160, 270, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_khoatk.setFont(font)
        self.btn_khoatk.setStyleSheet("background-color: rgb(255, 194, 209);\n"
"")
        self.btn_khoatk.setObjectName("btn_khoatk")
        self.btn_huylk = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_huylk.setGeometry(QtCore.QRect(330, 270, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_huylk.setFont(font)
        self.btn_huylk.setStyleSheet("background-color: rgb(255, 194, 209);\n"
"")
        self.btn_huylk.setObjectName("btn_huylk")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 40, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label.raise_()
        self.btn_return.raise_()
        self.tbl_lienketnh.raise_()
        self.btn_lktkmoi.raise_()
        self.btn_khoatk.raise_()
        self.btn_huylk.raise_()
        self.label_2.raise_()
        vilienket_form.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=vilienket_form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 18))
        self.menubar.setObjectName("menubar")
        vilienket_form.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=vilienket_form)
        self.statusbar.setObjectName("statusbar")
        vilienket_form.setStatusBar(self.statusbar)

        self.retranslateUi(vilienket_form)
        QtCore.QMetaObject.connectSlotsByName(vilienket_form)

    def retranslateUi(self, vilienket_form):
        _translate = QtCore.QCoreApplication.translate
        vilienket_form.setWindowTitle(_translate("vilienket_form", "Ví liên kết"))
        self.label.setText(_translate("vilienket_form", "<html><head/><body><p align=\"center\">Ví liên kết</p></body></html>"))
        self.btn_lktkmoi.setText(_translate("vilienket_form", "Liên kết tài khoản mới"))
        self.btn_khoatk.setText(_translate("vilienket_form", "Khóa / mở khóa tài khoản"))
        self.btn_huylk.setText(_translate("vilienket_form", "Hủy liên kết"))
        self.label_2.setText(_translate("vilienket_form", "Liên kết ngân hàng"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    vilienket_form = QtWidgets.QMainWindow()
    ui = Ui_vilienket_form()
    ui.setupUi(vilienket_form)
    vilienket_form.show()
    sys.exit(app.exec())
