# Form implementation generated from reading ui file 'xem_lai_quy.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_xem_lai_quy(object):
    def setupUi(self, xem_lai_quy):
        xem_lai_quy.setObjectName("xem_lai_quy")
        xem_lai_quy.resize(494, 370)
        self.centralwidget = QtWidgets.QWidget(parent=xem_lai_quy)
        self.centralwidget.setObjectName("centralwidget")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(-20, 0, 501, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(154, 205, 244);")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.btnQuayLai = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnQuayLai.setGeometry(QtCore.QRect(0, 0, 31, 31))
        self.btnQuayLai.setStyleSheet("background-color: rgba(245, 40, 145, 0);")
        self.btnQuayLai.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../ic_arrow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnQuayLai.setIcon(icon)
        self.btnQuayLai.setObjectName("btnQuayLai")
        self.tblXemLai = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tblXemLai.setGeometry(QtCore.QRect(20, 40, 440, 220))
        self.tblXemLai.setColumnCount(8)
        self.tblXemLai.setObjectName("tblXemLai")
        self.tblXemLai.setRowCount(0)
        self.btnXoa = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnXoa.setGeometry(QtCore.QRect(180, 270, 113, 32))
        self.btnXoa.setStyleSheet("background-color: rgb(255, 194, 209);\n"
"border-radius:10px")
        self.btnXoa.setObjectName("btnXoa")
        xem_lai_quy.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=xem_lai_quy)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 494, 24))
        self.menubar.setObjectName("menubar")
        xem_lai_quy.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=xem_lai_quy)
        self.statusbar.setObjectName("statusbar")
        xem_lai_quy.setStatusBar(self.statusbar)

        self.retranslateUi(xem_lai_quy)
        QtCore.QMetaObject.connectSlotsByName(xem_lai_quy)

    def retranslateUi(self, xem_lai_quy):
        _translate = QtCore.QCoreApplication.translate
        xem_lai_quy.setWindowTitle(_translate("xem_lai_quy", "Xem lại các quỹ"))
        self.label_5.setText(_translate("xem_lai_quy", "CÁC QUỸ ĐÃ TẠO"))
        self.btnXoa.setText(_translate("xem_lai_quy", "Xoá"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    xem_lai_quy = QtWidgets.QMainWindow()
    ui = Ui_xem_lai_quy()
    ui.setupUi(xem_lai_quy)
    xem_lai_quy.show()
    sys.exit(app.exec())
